### PR TITLE
Edited webserver to read "web server"

### PR DESCRIPTION
**Pull request by mikeshatch**

### CODE REVIEW

**Comment by eddiejaoude** [comment]
I always thought it was 1 word, so I just did a google and it is 2 words. Thank you for the contribution 🤓 👍

**Comment by eddiejaoude** [comment]
This change is from the source repository `revealjs`, you should contribute it to the main repo too 😉

**Comment by mikeshatch** [comment]
Thanks, Eddie. It's confusing because it looks like its own repo. The growing pains of learning to contribute...

**Comment by eddiejaoude** [comment]
Oh no, you are right! I didn't fork it, I think its because I have a fork of it already so I put it as a remote locally but on GitHub it is its own repo, my bad 🤦‍♂️ .

So you would need to fork the original repo and make a change and pull request to that one, that will give you another contribution 😉 , here is the original repo https://github.com/hakimel/reveal.js

**Comment by mikeshatch** [comment]
Ah, I see. No wonder I was confused. So why would I want to fork the original now? Why not just go to the original at the github address provided and do the same thing (make a pull request)?

**Comment by eddiejaoude** [comment]
Its will be the same - if you go to the original and create a pull request, you will need to fork the project first (if the contribution is done the GitHub UI it will automatically create a fork for you)

**Comment by mikeshatch** [comment]
Alright, cool.

**Pull request merged**
